### PR TITLE
Fix bug in decode delta

### PR DESCRIPTION
**Pull request by kmsquire**
This seems to be a code path that isn't taken often, but I ran into it.

### CODE REVIEW

**Comment by spapas** [comment]
Hey @kmsquire thank you for the PR. I see that you've changed the `a+=1` line to `r+=1`. Are you sure about that change? I usually use `a+=1` to add a breakpoint on my code, so maybe it's better to remove that line completely and don't mess with `r` at that time ? 

Unless you have tested the code as it is on a particular repo (that didn't work before) and works fine ?

**Comment by kmsquire** [comment]
Okay, made that change.  I don't think `r` is actually used as a return value anywhere yet, but it looks like it's an array, and given your use of `a += 1` as a breakpoint, it makes the most sense to remove it.

**Comment by spapas** [comment]
Thank you! Uploaded v 0.8.1 to pypi

**Comment by kmsquire** [comment]
Thank you!

**Pull request merged**
